/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 7 "exports_abicache.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 8 "exports_address.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 7 "exports_app.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 11 "exports_dev.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 10 "exports_membership.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 6 "exports_provider.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 6 "exports_signing.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 8 "exports_swap.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 6 "exports_transaction.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 8 "exports_wallet.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 19 "exports.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* GetCachedAbi(char* params);
extern char* SetCachedAbi(char* params);
extern char* ClearAbiCache(char* params);
extern char* ListContacts(char* params);
extern char* AddContact(char* params);
extern char* UpdateContact(char* params);
extern char* DeleteContact(char* params);
extern char* SetTransactionLabel(char* params);
extern char* GetTransactionLabels(char* params);
extern char* DeleteTransactionLabel(char* params);
extern char* GetAssetTransfers(char* params);
extern char* ValidatePassphrase(char* params);
extern char* IsFirstTimeSetup(char* params);
extern char* InitializeApp(char* params);
extern char* UnlockApp(char* params);
extern char* GetTokenBalances(char* params);
extern char* GetNFTs(char* params);
extern char* GetTokenApprovals(char* params);
extern char* CreateDevSession(char* params);
extern char* DevSessionSign(char* params);
extern char* GetDevSession(char* params);
extern char* EndDevSession(char* params);
extern char* GetMembershipStatus(char* params);
extern char* AddMembershipBinding(char* params);
extern char* RemoveMembershipBinding(char* params);
extern char* SyncMembershipBindingWithToken(char* params);
extern char* RemoveMembershipBindingWithToken(char* params);
extern char* CreateSessionToken(char* params);
extern char* ValidateSessionToken(char* params);
extern char* RevokeSessionToken(char* params);
extern char* GetDeviceMembershipStatusWithToken(char* params);
extern char* CreateWalletSessionToken(char* params);
extern char* ValidateWalletSessionToken(char* params);
extern char* RevokeWalletSessionToken(char* params);
extern char* SetProviderConfig(char* params);
extern char* GetProviderConfig(char* params);
extern char* ListProviderConfigs(char* params);
extern char* DeleteProviderConfig(char* params);
extern char* SignMessage(char* params);
extern char* SignTypedData(char* params);
extern char* GetSwapQuote(char* params);
extern char* BuildSwapTransaction(char* params);
extern char* GetSwapApproval(char* params);
extern char* CheckSwapAllowance(char* params);
extern char* GetNativeTokenAddress(void);
extern char* GetSwapTokens(char* params);
extern char* BuildTransaction(char* params);
extern char* SignTransaction(char* params);
extern char* BroadcastTransaction(char* params);
extern char* QueryTransactionStatus(char* params);
extern char* EstimateFee(char* params);
extern char* CheckTransactionSecurity(char* params);
extern char* CreateWallet(char* params);
extern char* ImportWallet(char* params);
extern char* UnlockWallet(char* params);
extern char* GenerateAddresses(char* params);
extern char* ExportWallet(char* params);
extern char* ImportBackupWallet(char* params);
extern char* ExportAllWallets(char* params);
extern char* ImportAllWallets(char* params);
extern char* RenameWallet(char* params);
extern char* DeleteWallet(char* params);
extern char* ListWallets(char* params);
extern void GoFree(char* ptr);
extern char* GetVersion(void);

#ifdef __cplusplus
}
#endif
