/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 19 "exports.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// GoFree frees memory allocated by Go and returned to Rust.
// CRITICAL: Rust MUST call this function on every pointer returned by FFI exports.
//
// Memory Safety:
// - Only call on pointers returned by this library's export functions
// - Never call twice on the same pointer (double-free)
// - Includes panic recovery to handle invalid pointers gracefully
extern void GoFree(char* ptr);

// GetVersion returns library version information as JSON.
// This is the simplest FFI function, useful for testing library loading.
//
// Returns: {"success": true, "data": {"version": "0.2.0", "buildTime": "...", "goVersion": "..."}}
// Caller MUST call GoFree() on the returned pointer.
extern char* GetVersion(void);

// CreateWallet creates a new HD wallet with auto-generated mnemonic.
// T021: Implement CreateWallet export function calling existing wallet.CreateWallet service
//
// Input JSON: {"walletName": "...", "password": "...", "usbPath": "...", "wordCount": 12|24, "passphrase": "..."}
// Output JSON: {"success": true, "data": {"walletId": "...", "walletName": "...", "mnemonic": "...", "createdAt": "..."}}
//
// Caller MUST call GoFree() on the returned pointer.
extern char* CreateWallet(char* params);

// ImportWallet imports an existing wallet from mnemonic.
// T022: Implement ImportWallet export function
//
// Input JSON: {"walletName": "...", "mnemonic": "...", "password": "...", "usbPath": "...", "passphrase": "..."}
// Output JSON: {"success": true, "data": {"walletId": "...", "walletName": "...", "importedAt": "..."}}
extern char* ImportWallet(char* params);

// UnlockWallet authenticates and loads wallet into memory.
// T023: Implement UnlockWallet export function with real password verification
//
// Input JSON: {"walletId": "...", "password": "...", "usbPath": "..."}
// Output JSON: {"success": true, "data": {"walletId": "...", "walletName": "...", "unlockedAt": "..."}}
extern char* UnlockWallet(char* params);

// GenerateAddresses derives addresses for specified blockchains from wallet's AddressBook.
// T024: Implement GenerateAddresses export function (returns all addresses from wallet metadata)
//
// Input JSON: {"walletId": "...", "blockchains": []}
// Output JSON: {"success": true, "data": {"addresses": [{"blockchain": "...", "address": "...", "derivationPath": "...", "symbol": "...", "coinType": ...}], "generatedAt": "..."}}
extern char* GenerateAddresses(char* params);

// ExportWallet exports wallet metadata without private keys.
// T024.1: Implement ExportWallet export function
//
// Input JSON: {"walletName": "...", "usbPath": "...", "format": "json"}
// Output JSON: {"success": true, "data": {"walletId": "...", "walletName": "...", "exportData": "...", "exportedAt": "..."}}
extern char* ExportWallet(char* params);

// RenameWallet changes wallet display name.
// T024.2: Implement RenameWallet export function
//
// Input JSON: {"walletName": "...", "newWalletName": "...", "usbPath": "..."}
// Output JSON: {"success": true, "data": {"walletId": "...", "oldName": "...", "newName": "...", "renamedAt": "..."}}
extern char* RenameWallet(char* params);

// DeleteWallet permanently deletes a wallet from storage after password verification.
// This is a destructive operation that cannot be undone.
//
// Security: Requires correct wallet password for authentication.
//
// Input JSON: {
//   "walletId": "uuid",
//   "password": "wallet-password",  // REQUIRED: Must be correct
//   "usbPath": "/path/to/usb"
// }
//
// Returns: {"success": true, "data": {"walletId": "...", "deletedAt": "..."}}
extern char* DeleteWallet(char* params);

// ListWallets enumerates all wallets on USB.
// T024.3: Implement ListWallets export function
//
// Input JSON: {"usbPath": "..."}
// Output JSON: {"success": true, "data": {"wallets": [{"walletId": "...", "walletName": "...", "createdAt": "..."}], "count": 2}}
extern char* ListWallets(char* params);

// BuildTransaction constructs an unsigned transaction ready for signing.
// Feature: 006-chain-adapter - ChainAdapter Transaction FFI
//
// Input JSON: {
//   "chainId": "bitcoin" | "ethereum" | "ethereum-sepolia",
//   "from": "address",
//   "to": "address",
//   "asset": "BTC" | "ETH",
//   "amount": "1000000",  // string representation of big.Int
//   "feeSpeed": "slow" | "normal" | "fast",
//   "memo": "optional",
//   "tokenAddress": "optional ERC-20 contract address",
//   "usbPath": "/path/to/usb",
//   "appPassword": "app-password"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "id": "unique-tx-id",
//     "chainId": "bitcoin",
//     "from": "address",
//     "to": "address",
//     "amount": "1000000",
//     "fee": "5000",
//     "signingPayload": "base64-encoded-bytes",
//     "humanReadable": "JSON representation for audit"
//   }
// }
extern char* BuildTransaction(char* params);

// SignTransaction signs an unsigned transaction using wallet password.
// Feature: 006-chain-adapter - ChainAdapter Transaction FFI
//
// Security Design:
// - Private key is derived on-demand from mnemonic using password
// - Private key exists only during signing (~50-100ms)
// - All sensitive data (password, mnemonic, privateKey) cleared after use
//
// Input JSON: {
//   "walletId": "uuid-xxx",
//   "password": "user-password",
//   "passphrase": "bip39-passphrase",  // Optional BIP39 passphrase (empty string if not used)
//   "usbPath": "/path/to/usb",
//   "chainId": "bitcoin" | "ethereum",
//   "unsignedTx": {...}  // UnsignedTransaction from BuildTransaction (includes "from" address)
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "txHash": "0x...",
//     "signature": "base64-encoded-signature",
//     "serializedTx": "base64-encoded-serialized-tx",
//     "signedBy": "address"
//   }
// }
extern char* SignTransaction(char* params);

// BroadcastTransaction submits a signed transaction to the blockchain network.
// Feature: 006-chain-adapter - ChainAdapter Transaction FFI
//
// Input JSON: {
//   "chainId": "bitcoin" | "ethereum",
//   "signedTx": {...},  // SignedTransaction from SignTransaction
//   "rpcConfig": "optional-rpc-endpoint"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "txHash": "0x...",
//     "chainId": "bitcoin",
//     "submittedAt": "2025-11-04T15:30:00Z",
//     "status": "pending",
//     "statusUrl": "https://blockexplorer.com/tx/..."
//   }
// }
extern char* BroadcastTransaction(char* params);

// QueryTransactionStatus retrieves the current status of a transaction.
// Feature: 006-chain-adapter - ChainAdapter Transaction FFI
//
// Input JSON: {
//   "chainId": "bitcoin" | "ethereum",
//   "txHash": "0x..." | "bitcoin-tx-hash",
//   "rpcConfig": "optional-rpc-endpoint"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "txHash": "0x...",
//     "status": "pending" | "confirmed" | "finalized" | "failed",
//     "confirmations": 3,
//     "blockNumber": 12345,
//     "blockHash": "0x...",
//     "updatedAt": "2025-11-04T15:35:00Z"
//   }
// }
extern char* QueryTransactionStatus(char* params);

// SetProviderConfig saves a blockchain data provider configuration.
// Feature: Provider Registry System - API Key Management
//
// Input JSON: {
//   "providerType": "alchemy" | "infura" | "quicknode",
//   "apiKey": "your-api-key",
//   "chainId": "ethereum",
//   "networkId": "mainnet" | "sepolia",  // Optional
//   "customEndpoint": "https://...",      // Optional
//   "priority": 100,                      // Higher = preferred
//   "enabled": true,
//   "password": "wallet-password",        // For encryption
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "providerType": "alchemy",
//     "chainId": "ethereum",
//     "configured": true,
//     "configuredAt": "2025-11-27T10:00:00Z"
//   }
// }
extern char* SetProviderConfig(char* params);

// GetProviderConfig retrieves a blockchain data provider configuration.
// Feature: Provider Registry System - API Key Management
//
// Input JSON: {
//   "chainId": "ethereum",
//   "providerType": "alchemy",  // Optional: if not specified, returns best provider
//   "password": "wallet-password",
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "providerType": "alchemy",
//     "chainId": "ethereum",
//     "networkId": "mainnet",
//     "priority": 100,
//     "enabled": true,
//     "hasApiKey": true,
//     "createdAt": "2025-11-27T09:00:00Z",
//     "updatedAt": "2025-11-27T10:00:00Z"
//   }
// }
extern char* GetProviderConfig(char* params);

// ListProviderConfigs retrieves all provider configurations for a chain.
// Feature: Provider Registry System - API Key Management
//
// Input JSON: {
//   "chainId": "ethereum",  // Optional: if not specified, lists all chains
//   "password": "wallet-password",
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "providers": [
//       {
//         "providerType": "alchemy",
//         "chainId": "ethereum",
//         "priority": 100,
//         "enabled": true
//       },
//       {...}
//     ],
//     "count": 2
//   }
// }
extern char* ListProviderConfigs(char* params);

// DeleteProviderConfig removes a provider configuration.
// Feature: Provider Registry System - API Key Management
//
// Input JSON: {
//   "chainId": "ethereum",
//   "providerType": "alchemy",
//   "password": "wallet-password",
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "deleted": true,
//     "deletedAt": "2025-11-27T10:05:00Z"
//   }
// }
extern char* DeleteProviderConfig(char* params);

// EstimateFee calculates fee estimates with confidence bounds.
// Feature: 006-chain-adapter - ChainAdapter Transaction FFI
//
// Input JSON: {
//   "chainId": "bitcoin" | "ethereum",
//   "from": "address",
//   "to": "address",
//   "asset": "BTC" | "ETH",
//   "amount": "1000000",
//   "rpcConfig": "optional-rpc-endpoint"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "chainId": "bitcoin",
//     "minFee": "1000",
//     "recommendedFee": "5000",
//     "maxFee": "10000",
//     "confidence": 85,
//     "estimatedBlocks": 6,
//     "timestamp": "2025-11-04T15:40:00Z"
//   }
// }
extern char* EstimateFee(char* params);

// IsFirstTimeSetup checks if app_config.enc exists at the USB path.
// Feature: App-level authentication
//
// Input JSON: {
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "isFirstTime": true  // true if app_config.enc doesn't exist
//   }
// }
extern char* IsFirstTimeSetup(char* params);

// InitializeApp creates a new encrypted app_config.enc file for first-time setup.
// Feature: App-level authentication
//
// Input JSON: {
//   "password": "user-master-password",
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "message": "App initialized successfully"
//   }
// }
extern char* InitializeApp(char* params);

// UnlockApp decrypts and loads app_config.enc using the provided password.
// Feature: App-level authentication
//
// Input JSON: {
//   "password": "user-master-password",
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "config": {
//       "version": "1.0.0",
//       "wallets": [{"id": "...", "name": "...", "createdAt": "..."}],
//       "providers": [{"providerType": "alchemy", "apiKey": "...", "priority": 100, "enabled": true}],
//       "settings": {"theme": "light", "language": "en"}
//     }
//   }
// }
extern char* UnlockApp(char* params);

// GetTokenBalances queries token balances for all addresses in a wallet across multiple chains
// using Alchemy API. Returns aggregated token balances with USD values.
//
// Security: Requires valid wallet password for authentication before accessing balance data.
//
// Input JSON: {
//   "walletId": "uuid",
//   "password": "wallet-password",  // REQUIRED: Must be correct wallet password
//   "usbPath": "/path/to/usb",
//   "appPassword": "app-level-password"
// }
//
// Returns: {"success": true, "data": {"tokens": [...], "totalUsd": 5000.50, ...}}
extern char* GetTokenBalances(char* params);

// GetAssetTransfers queries transaction history for an address using Alchemy API.
// Feature: Transaction History - Asset Transfers API Integration
//
// Input JSON: {
//   "address": "0x...",           // The wallet address to query
//   "network": "eth-mainnet",     // Network identifier (eth-mainnet, polygon-mainnet, etc.)
//   "maxCount": 50,               // Optional: maximum number of transfers to return
//   "pageKey": "",                // Optional: pagination key for next page
//   "appPassword": "app-password",
//   "usbPath": "/path/to/usb"
// }
//
// Returns: {"success": true, "data": {"transfers": [...], "pageKey": "..."}}
extern char* GetAssetTransfers(char* params);

// ValidatePassphrase validates a BIP39 passphrase by deriving an Ethereum address
// and comparing it with the stored address in the wallet's AddressBook.
// Feature: Passphrase validation for wallets with BIP39 passphrase
//
// This is used during wallet unlock flow:
// 1. User enters wallet password (validated via unlock_wallet)
// 2. If wallet has_passphrase=true, user is prompted for passphrase
// 3. This function validates the passphrase by comparing derived address
//
// Input JSON: {
//   "walletId": "uuid-xxx",
//   "password": "user-password",
//   "passphrase": "bip39-passphrase",
//   "usbPath": "/path/to/usb"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "valid": true,
//     "derivedAddress": "0x...",
//     "expectedAddress": "0x..."
//   }
// }
extern char* ValidatePassphrase(char* params);

// GetSwapQuote fetches a swap quote from OpenOcean DEX aggregator.
// Feature: Token Swap (OpenOcean - FREE, No KYC required)
//
// Input JSON: {
//   "chainId": "ethereum" | "polygon" | "arbitrum" | etc.,
//   "fromTokenAddress": "0x..." or "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE" for native,
//   "toTokenAddress": "0x...",
//   "amount": "1000000000000000000",  // Amount in smallest unit (wei)
//   "fromAddress": "0x...",  // User's wallet address
//   "slippage": 0.5,  // Slippage tolerance in percent
//   "usbPath": "/path/to/usb",
//   "appPassword": "password"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "dex": "OpenOcean",
//     "fromToken": {...},
//     "toToken": {...},
//     "fromAmount": "...",
//     "toAmount": "...",
//     "toAmountMin": "...",
//     "exchangeRate": "...",
//     "estimatedGas": "...",
//     "gasCostETH": "...",
//     "route": ["ETH", "USDC"],
//     "protocols": ["OpenOcean"],
//     "needsApproval": true,
//     "approvalAddress": "0x..."
//   }
// }
extern char* GetSwapQuote(char* params);

// BuildSwapTransaction builds a complete swap transaction ready for signing.
// Feature: Token Swap
//
// Input JSON: same as GetSwapQuote
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "quote": {...},  // Same as GetSwapQuote response
//     "txData": {
//       "from": "0x...",
//       "to": "0x...",  // 1inch router
//       "data": "0x...",  // Encoded swap call
//       "value": "0",  // ETH value for native swaps
//       "gas": 200000
//     },
//     "chainId": 1
//   }
// }
extern char* BuildSwapTransaction(char* params);

// GetSwapApproval builds the ERC-20 approve transaction data locally.
// This does NOT call any external API - it just encodes the approve(spender, amount) call.
// Feature: Token Swap - Approval Flow
//
// Input JSON: {
//   "chainId": "ethereum",
//   "tokenAddress": "0x...",  // Token contract to call approve() on
//   "spenderAddress": "0x...", // DEX router address (from quote.approvalAddress)
//   "amount": "1000000000000000000",  // Amount to approve (optional, empty = unlimited = MaxUint256)
//   "usbPath": "/path/to/usb",
//   "appPassword": "password"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "to": "0x...",  // Token contract address
//     "data": "0x...",  // Encoded approve(spender, amount) call
//     "value": "0"
//   }
// }
extern char* GetSwapApproval(char* params);

// CheckSwapAllowance checks the current token allowance for 1inch router.
// Feature: Token Swap - Allowance Check
//
// Input JSON: {
//   "chainId": "ethereum",
//   "tokenAddress": "0x...",
//   "walletAddress": "0x...",
//   "usbPath": "/path/to/usb",
//   "appPassword": "password"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "allowance": "1000000000000000000",
//     "hasAllowance": true
//   }
// }
extern char* CheckSwapAllowance(char* params);

// GetNativeTokenAddress returns the standard native token address for DEX APIs.
// Native tokens (ETH, MATIC, BNB, etc.) use this special address in API calls.
extern char* GetNativeTokenAddress(void);

// GetSwapTokens fetches all available tokens for swap on a chain from OpenOcean API.
// Feature: Token Swap (OpenOcean - FREE, No KYC required)
//
// Input JSON: {
//
//	"chainId": "56",  // Chain ID as string
//	"usbPath": "/Volumes/USB/...",
//	"appPassword": "password123"
//
// }
//
// Output JSON: {
//
//	"success": true,
//	"data": {
//	  "tokens": [
//	    {
//	      "symbol": "BNB",
//	      "name": "BNB",
//	      "address": "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE",
//	      "decimals": 18,
//	      "logoURI": "https://..."
//	    },
//	    ...
//	  ]
//	}
//
// }
extern char* GetSwapTokens(char* params);

// GetMembershipStatus returns the USB device identity and membership status.
// This also ensures the deviceId is generated if it doesn't exist.
//
// Input JSON: {
//   "usbPath": "/path/to/usb",
//   "appPassword": "password"
// }
//
// Output JSON: {
//   "success": true,
//   "data": {
//     "deviceId": "uuid-string",
//     "deviceIdHash": "0x...",  // keccak256(deviceId) for contract binding
//     "walletLimit": 3,
//     "walletCount": 1,
//     "canCreateWallet": true,
//     "memberships": [{
//       "nftTokenId": "1",
//       "nftContract": "0x...",
//       "chainId": "bnb",
//       "boundAddress": "0x...",
//       "isValid": true
//     }]
//   }
// }
extern char* GetMembershipStatus(char* params);

// AddMembershipBinding adds a new NFT membership binding to this USB device.
// Call this after the user has bound their deviceId on the NFT contract.
//
// Input JSON: {
//   "usbPath": "/path/to/usb",
//   "appPassword": "password",
//   "nftTokenId": "1",
//   "nftContract": "0x...",
//   "chainId": "bnb",
//   "boundAddress": "0x...",
//   "signature": "0x..."
// }
extern char* AddMembershipBinding(char* params);

// RemoveMembershipBinding removes an NFT membership binding from this USB device.
//
// Input JSON: {
//   "usbPath": "/path/to/usb",
//   "appPassword": "password",
//   "nftTokenId": "1",
//   "nftContract": "0x..."
// }
extern char* RemoveMembershipBinding(char* params);
extern char* CreateSessionToken(char* params);
extern char* ValidateSessionToken(char* params);
extern char* RevokeSessionToken(char* params);
extern char* GetDeviceMembershipStatusWithToken(char* params);
extern char* CreateWalletSessionToken(char* params);
extern char* ValidateWalletSessionToken(char* params);
extern char* RevokeWalletSessionToken(char* params);

#ifdef __cplusplus
}
#endif
